# Generated by Django 3.1.11 on 2021-09-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmenttemplate',
            old_name='section_fields',
            new_name='data_fields',
        ),
        migrations.RenameField(
            model_name='historicalassessmenttemplate',
            old_name='section_fields',
            new_name='data_fields',
        ),
        migrations.RemoveField(
            model_name='division',
            name='data_fields',
        ),
        migrations.RemoveField(
            model_name='section',
            name='division_fields',
        ),
    ]
