# Generated by Django 3.1.11 on 2021-09-16 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexio', '0003_auto_20210916_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='division', to='flexio.section'),
        ),
        migrations.AlterField(
            model_name='field',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='field', to='flexio.division'),
        ),
    ]
