# Generated by Django 3.1.11 on 2021-09-16 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexio', '0006_auto_20210916_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='inventory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_join', to='flexio.inventoryjoin'),
        ),
    ]
