# Generated by Django 3.1.11 on 2021-09-27 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flexio', '0009_auto_20210922_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmenttemplate',
            name='revision_number',
        ),
        migrations.RemoveField(
            model_name='historicalassessmenttemplate',
            name='revision_number',
        ),
        migrations.AlterField(
            model_name='assessmenttemplate',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='historicalassessmenttemplate',
            name='last_modified',
            field=models.DateTimeField(blank=True, editable=False),
        ),
    ]
