# Generated by Django 3.1.11 on 2021-09-27 09:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flexio', '0011_historicaldivision_historicalfield_historicalsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttemplate',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalassessmenttemplate',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
    ]
