# Generated by Django 3.1.11 on 2021-10-05 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexio', '0012_auto_20210927_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow_Up_Join',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AlterField(
            model_name='section',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_join', to='flexio.inventoryjoin'),
        ),
        migrations.AddField(
            model_name='followupquestion',
            name='follow_up',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up', to='flexio.follow_up_join'),
        ),
    ]
