# Generated by Django 3.1.11 on 2021-10-05 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexio', '0013_auto_20211005_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='follow_up_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_question', to='flexio.follow_up_join'),
        ),
        migrations.AlterField(
            model_name='historicalfield',
            name='follow_up_question',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flexio.follow_up_join'),
        ),
    ]
