# Generated by Django 3.1.11 on 2021-10-05 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexio', '0014_auto_20211005_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldivision',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldivision',
            name='section',
        ),
        migrations.RemoveField(
            model_name='field',
            name='division',
        ),
        migrations.RemoveField(
            model_name='historicalfield',
            name='division',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='HistoricalDivision',
        ),
    ]
