# Generated by Django 3.1.11 on 2021-10-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexio', '0015_auto_20211005_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flexio.section'),
        ),
        migrations.AddField(
            model_name='historicalfield',
            name='section',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flexio.section'),
        ),
    ]
