# Generated by Django 3.1.11 on 2021-10-07 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexio', '0018_auto_20211005_1603'),
    ]

    operations = [
        migrations.RenameModel('Follow_Up_Join', 'FollowUpJoin')

    ]
