# Generated by Django 3.1.11 on 2022-02-11 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flexio', '0019_auto_20211007_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='follow_up_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_up_question', to='flexio.followupjoin'),
        ),
    ]
