# Generated by Django 3.2.12 on 2022-03-08 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flexio', '0020_auto_20220211_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsection',
            name='floor_plan',
        ),
        migrations.RemoveField(
            model_name='postimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='section',
            name='floor_plan',
        ),
    ]
