# Generated by Django 4.0.1 on 2022-03-07 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_delete_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_number', models.CharField(max_length=10, verbose_name='Rates')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
                ('price', models.FloatField()),
            ],
        ),
    ]
