# Generated by Django 4.0.1 on 2022-03-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_unwantedwords'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, verbose_name='Username')),
                ('word', models.CharField(max_length=25, verbose_name='Word Used')),
                ('date', models.DateField()),
            ],
        ),
    ]
