# Generated by Django 4.0.1 on 2022-03-08 09:53

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_blockcontacts_date_alter_ratescomments_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockcontacts',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ratescomments',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 3, 8, 9, 53, 1, 843192, tzinfo=utc)),
        ),
    ]
