# Generated by Django 4.0.1 on 2022-03-08 10:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_blockcontacts_date_alter_ratescomments_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarrifs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Description')),
                ('tarrif_number', models.CharField(max_length=10, verbose_name='Tarrif Number')),
                ('amount', models.FloatField()),
                ('updat_date', models.DateTimeField()),
                ('username', models.CharField(max_length=25, verbose_name='Changed by')),
            ],
        ),
        migrations.AlterField(
            model_name='blockcontacts',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ratescomments',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 8, 10, 47, 4, 686940, tzinfo=utc)),
        ),
    ]
