# Generated by Django 4.0.1 on 2022-03-08 19:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_ratescomments_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarrifs',
            old_name='username',
            new_name='usernames',
        ),
        migrations.AlterField(
            model_name='ratescomments',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 8, 19, 41, 13, 585595, tzinfo=utc)),
        ),
    ]
