# Generated by Django 4.0.1 on 2022-03-08 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_rename_username_tarrifs_usernames_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarrifs',
            old_name='usernames',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='ratescomments',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 8, 19, 42, 35, 337104, tzinfo=utc)),
        ),
    ]
