# Generated by Django 4.0.3 on 2022-04-21 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_usernames_tarrifs_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarrifs',
            name='comment',
            field=models.CharField(blank=True, max_length=500, verbose_name='Reason for Price'),
        ),
        migrations.AlterField(
            model_name='ratescomments',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='%Y-%m-%d T%H:%M'),
        ),
    ]
