<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-05-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratescomments',
            name='grade',
            field=models.CharField(blank=True, max_length=1, verbose_name='Grade'),
        ),
    ]
=======
# Generated by Django 4.0.3 on 2022-05-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratescomments',
            name='grade',
            field=models.CharField(blank=True, max_length=1, verbose_name='Grade'),
        ),
    ]
>>>>>>> parent of 5a30ca7... commit message
