<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-05-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_ratescomments_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_viewuser',
                'managed': False,
            },
        ),
    ]
=======
# Generated by Django 4.0.3 on 2022-05-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_ratescomments_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewUser',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'users_viewuser',
                'managed': False,
            },
        ),
    ]
>>>>>>> parent of 5a30ca7... commit message
