<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-05-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
=======
# Generated by Django 4.0.3 on 2022-05-27 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
>>>>>>> parent of 5a30ca7... commit message
