<<<<<<< HEAD
# Generated by Django 4.0.3 on 2022-05-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratescomments',
            old_name='username',
            new_name='usern',
        ),
    ]
=======
# Generated by Django 4.0.3 on 2022-05-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratescomments',
            old_name='username',
            new_name='usern',
        ),
    ]
>>>>>>> parent of 5a30ca7... commit message
