# Generated by Django 4.0.3 on 2022-05-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_rename_username_ratescomments_usern'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ratescomments',
            old_name='usern',
            new_name='username',
        ),
    ]
