const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const ApplyBusiness = new Schema({
  firstName: String,
  lastName: String,
  age: String,
  period: String,
  gender: String,
  emailAddress: String,
  mobileNumber: String,
  streetAddress: String,
  city: String,
  state: String,
  postalCode: String,
  pregnant: String,
  admitted: String,
  travelled: String,
  visitedCountry: String,
  returnDate: String,
  duration: String,
  durationUnit: String,
  visitor: String,
  reasonForTravel: String,
  chemoprophylaxis: String,
  drugsChemoprophylaxis: String,
  hadMalaria: String,
  illnessDate: String,
  speciesDisease: String,
  fever: String,
  flu: String,
  shakingChills: String,
  Nausea: String,
  vomiting: String,
  headache: String,
  musclePain: String,
  diarrhea: String,
  tiredness: String,
  comments: String,
  deduced: String,
  Facility: String,
  date: String,
});

module.exports = mongoose.model('Apply', ApplyBusiness);
