# Generated by Django 3.1.1 on 2022-05-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen', '0002_customer_amount_spent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.TextField(null=True),
        ),
    ]
